### ISSUE TITLE
Saving settings

### ISSUE THREAD

**Issue by antgibson96** [ConjuredInfinity/NewsroomApp#5]
We need to save the settings that the use selects so they don't have to add rss feeds or filter them out every time they open the app.

**Comment by gatorryan25** [comment]
There is the SharedPreferences object that lets you store and call the preferences back later. We could save a string that contains the rss feeds they want and just pull those up. I used SharedPreferences for remembering nightmode and shake to refresh

**Comment by camanjj** [comment]
That is what I added the RssService for. To add, list and remove the rss items in persistent storage
